### ISSUE TITLE
rename of theme

### ISSUE THREAD

**Issue by Nwillia3** [gatsbymanor/gatsby-themes-starter#3]
When I enter the command gatsby new themes/identity gatsbymanor/gatsby-theme-identity it changes my theme to identity. If I continue with the tutorial, an error is raised when I run the command gatsby develop --enabled-themes. 

This error is shown:
Error: Cannot find module '/Users/sharode/Desktop/gatsby-themes-starter/themes/gatsby-theme-identity/package.json'

<img width="258" alt="screen shot 2018-08-02 at 8 46 13 pm" src="https://user-images.githubusercontent.com/14264004/43618514-d5d9a444-9696-11e8-89be-ef08b3824861.png">

**Comment by nodox** [comment]
The reason why this occurs is because the command 
```
gatsby new themes/identity gatsbymanor/gatsby-theme-identity
```
Clones the gatsby-theme-identity theme to your themes folder as identity. You can see that in the argument provided after the `new` command. To fix this you would have to 

- rename the theme in the themes folder
- rename the theme in the `gatsby-theme.yaml` file.

Let me know if that makes sense or if that fixed the issue.
